#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/emergency_transport_roads/kumamoto_emergency_transport_roads_2024_preprocessed.parquet
Output: data/processed/emergency_transport_roads_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/emergency_transport_roads/kumamoto_emergency_transport_roads_2024_preprocessed.parquet"
dst = ROOT / "data/processed/emergency_transport_roads_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Prefecture Code": "Prefecture Code",
    "Emergency Road Class Code": "Emergency Road Class Code",
    "Road Type Code": "Road Type Code",
    "Route Name": "Route Name",
    "Route ID": "Route ID",
    "Branch ID": "Branch ID",
    "Source Name": "Source Name",
    "Source Date": "Source Date",
    "Service Status": "Service Status",
    "Notes": "Notes",
    "Geometry": "Geometry",
    "Emergency Road Class": "Emergency Road Class",
    "Road Type": "Road Type",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
