#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01d/road_restriction_edge_matches/road_restriction_edge_matches_preprocessed.parquet
Output: data/processed/road_restriction_edge_matches_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01d/road_restriction_edge_matches/road_restriction_edge_matches_preprocessed.parquet"
dst = ROOT / "data/processed/road_restriction_edge_matches_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Restriction Observation ID": "Restriction Observation ID",
    "Snapshot Time": "Snapshot Time",
    "Route Name": "Route Name",
    "Restriction Status": "Restriction Status",
    "Restriction Reason": "Restriction Reason",
    "Geometry": "Geometry",
    "Matched Road Edge ID": "Matched Road Edge ID",
    "Road Edge Match Distance (m)": "Road Edge Match Distance (m)",
    "Route Name Agreement": "Route Name Agreement",
    "Road Edge Match Candidate Count": "Road Edge Match Candidate Count",
    "Road Edge Match Method": "Road Edge Match Method",
    "Road Edge Match Status": "Road Edge Match Status",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
