#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01c/earthquake_damage_evidence/earthquake_damage_evidence_reference_preprocessed.parquet
Output: data/processed/earthquake_damage_evidence_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01c/earthquake_damage_evidence/earthquake_damage_evidence_reference_preprocessed.parquet"
dst = ROOT / "data/processed/earthquake_damage_evidence_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Evidence ID": "Evidence ID",
    "Event ID": "Event ID",
    "Observation Time": "Observation Time",
    "Municipality": "Municipality",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Coordinate Precision": "Coordinate Precision",
    "Coordinate Uncertainty (m)": "Coordinate Uncertainty (m)",
    "Evidence Tier": "Evidence Tier",
    "Verification Status": "Verification Status",
    "Asset Type": "Asset Type",
    "Observed Damage Type": "Observed Damage Type",
    "Structural Damage Class": "Structural Damage Class",
    "Reported Affected Asset Count": "Reported Affected Asset Count",
    "Place Description": "Place Description",
    "Source Organization": "Source Organization",
    "Source Type": "Source Type",
    "Source Report Number": "Source Report Number",
    "Source Page": "Source Page",
    "Source URL": "Source URL",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
