#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/landslide_warning_zones/kumamoto_landslide_warning_zones_2025_preprocessed.parquet
Output: data/processed/landslide_warning_zones_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/landslide_warning_zones/kumamoto_landslide_warning_zones_2025_preprocessed.parquet"
dst = ROOT / "data/processed/landslide_warning_zones_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Hazard Type Code": "Hazard Type Code",
    "Warning Zone Class Code": "Warning Zone Class Code",
    "Prefecture Code": "Prefecture Code",
    "Zone ID": "Zone ID",
    "Zone Name": "Zone Name",
    "Address": "Address",
    "Designation Date": "Designation Date",
    "Special Warning Zone Pending Code": "Special Warning Zone Pending Code",
    "Geometry": "Geometry",
    "Hazard Type": "Hazard Type",
    "Warning Zone Class": "Warning Zone Class",
    "Special Warning Zone Pending": "Special Warning Zone Pending",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
