#!/usr/bin/env python3
"""Preprocessing script for data/exp/acquisition-audit/official_threshold_factors.csv
Output: data/processed/official_threshold_factors_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/exp/acquisition-audit/official_threshold_factors.csv"
dst = ROOT / "data/processed/official_threshold_factors_preprocessed.parquet"

# --- Load ---
df = pd.read_csv(src, encoding="utf-8-sig", low_memory=False)

# --- Select and rename columns ---
rename_map = {
    "temporary_threshold_group": "Temporary Threshold Group",
    "baseline_fraction": "Rainfall Threshold Retention Factor",
    "municipality_or_subarea": "Municipality or Subarea (Japanese)",
    "source": "Source",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Temporary Threshold Group
df["Temporary Threshold Group"] = df["Temporary Threshold Group"].str.strip()
# Rainfall Threshold Retention Factor
df["Rainfall Threshold Retention Factor"] = pd.to_numeric(df["Rainfall Threshold Retention Factor"], errors="coerce")
# Municipality or Subarea (Japanese)
df["Municipality or Subarea (Japanese)"] = df["Municipality or Subarea (Japanese)"].str.strip()
# Source
df["Source"] = df["Source"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
