#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/population_disclosure_groups/kumamoto_population_disclosure_groups_preprocessed.parquet
Output: data/processed/population_disclosure_groups_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/population_disclosure_groups/kumamoto_population_disclosure_groups_preprocessed.parquet"
dst = ROOT / "data/processed/population_disclosure_groups_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Disclosure Group Code": "Disclosure Group Code",
    "Geometry": "Geometry",
    "Disclosure Group Size": "Disclosure Group Size",
    "Suppressed Source Mesh Count": "Suppressed Source Mesh Count",
    "Total Population": "Total Population",
    "Total Households": "Total Households",
    "General Households": "General Households",
    "Population Age 65+": "Population Age 65+",
    "Population Age 75+": "Population Age 75+",
    "Population Age 85+": "Population Age 85+",
    "One-Person Households": "One-Person Households",
    "Households with Member Age 65+": "Households with Member Age 65+",
    "Older Single-Person Households": "Older Single-Person Households",
    "Older Couple Households": "Older Couple Households",
    "Population Age 65+ Share": "Population Age 65+ Share",
    "Population Age 75+ Share": "Population Age 75+ Share",
    "Population Age 85+ Share": "Population Age 85+ Share",
    "Older Single-Person Household Share": "Older Single-Person Household Share",
    "Older Couple Household Share": "Older Couple Household Share",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
