#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01c/designated_shelters/designated_shelters_preprocessed.parquet
Output: data/processed/designated_shelters_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01c/designated_shelters/designated_shelters_preprocessed.parquet"
dst = ROOT / "data/processed/designated_shelters_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Shelter ID": "Shelter ID",
    "Shelter Name": "Shelter Name",
    "Same Address as Emergency Evacuation Site": "Same Address as Emergency Evacuation Site",
    "Accepted Persons": "Accepted Persons",
    "Geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
