#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01d/current_shelters/shelters_current_preprocessed.parquet
Output: data/processed/current_shelters_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01d/current_shelters/shelters_current_preprocessed.parquet"
dst = ROOT / "data/processed/current_shelters_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Municipality": "Municipality",
    "Shelter Number": "Shelter Number",
    "Shelter Name": "Shelter Name",
    "District": "District",
    "Maximum Capacity": "Maximum Capacity",
    "Evacuee Households": "Evacuee Households",
    "Evacuee People": "Evacuee People",
    "Water Status": "Water Status",
    "Electricity Status": "Electricity Status",
    "Air Conditioning Status": "Air Conditioning Status",
    "Toilet Count": "Toilet Count",
    "Portable Toilet Count": "Portable Toilet Count",
    "Snapshot Time": "Snapshot Time",
    "Source URL": "Source URL",
    "Source File": "Source File",
    "Source Retrieved At UTC": "Source Retrieved At UTC",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Location Resolution Status": "Location Resolution Status",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
