#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/road_edges/kumamoto_routable_road_edges_preprocessed.parquet
Output: data/processed/road_edges_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/road_edges/kumamoto_routable_road_edges_preprocessed.parquet"
dst = ROOT / "data/processed/road_edges_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Road Edge ID": "Road Edge ID",
    "Road Section ID": "Road Section ID",
    "From Node ID": "From Node ID",
    "To Node ID": "To Node ID",
    "Network Component ID": "Network Component ID",
    "Road Length (m)": "Road Length (m)",
    "Assumed Speed (km/h)": "Assumed Speed (km/h)",
    "Baseline Edge Travel Time (min)": "Baseline Edge Travel Time (min)",
    "Hazard Exposure Class": "Hazard Exposure Class",
    "Emergency Route Membership": "Emergency Route Membership",
    "Road Available": "Road Available",
    "Network Analysis Eligible": "Network Analysis Eligible",
    "Route ID": "Route ID",
    "Route Name": "Route Name",
    "Road Category": "Road Category",
    "Road State": "Road State",
    "Vertical Level": "Vertical Level",
    "Width Category": "Width Category",
    "Toll Category": "Toll Category",
    "Secondary Mesh Code": "Secondary Mesh Code",
    "Geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
