#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/evacuation_facilities/kumamoto_evacuation_facilities_2012_preprocessed.parquet
Output: data/processed/evacuation_facilities_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/evacuation_facilities/kumamoto_evacuation_facilities_2012_preprocessed.parquet"
dst = ROOT / "data/processed/evacuation_facilities_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Municipality Code": "Municipality Code",
    "Facility Name": "Facility Name",
    "Address": "Address",
    "Facility Type": "Facility Type",
    "Capacity": "Capacity",
    "Facility Area m2": "Facility Area m2",
    "Earthquake Hazard": "Earthquake Hazard",
    "Tsunami Hazard": "Tsunami Hazard",
    "Flood Hazard": "Flood Hazard",
    "Volcanic Hazard": "Volcanic Hazard",
    "Other Hazard": "Other Hazard",
    "No Hazard Specified": "No Hazard Specified",
    "Location Accuracy Level": "Location Accuracy Level",
    "Notes": "Notes",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Source Record ID": "Source Record ID",
    "Geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
