#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/fire_stations/kumamoto_fire_stations_2012_preprocessed.parquet
Output: data/processed/fire_stations_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/fire_stations/kumamoto_fire_stations_2012_preprocessed.parquet"
dst = ROOT / "data/processed/fire_stations_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Fire Facility Name": "Fire Facility Name",
    "Municipality Code": "Municipality Code",
    "Fire Facility Type Code": "Fire Facility Type Code",
    "Address": "Address",
    "Geometry": "Geometry",
    "Fire Facility Type": "Fire Facility Type",
    "Candidate Dispatch Base": "Candidate Dispatch Base",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
