#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01d/emergency_water_points/emergency_water_points_preprocessed.parquet
Output: data/processed/emergency_water_points_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01d/emergency_water_points/emergency_water_points_preprocessed.parquet"
dst = ROOT / "data/processed/emergency_water_points_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Municipality": "Municipality",
    "Water Point Name": "Water Point Name",
    "Valid From Date": "Valid From Date",
    "Valid To Date": "Valid To Date",
    "Opening Time": "Opening Time",
    "Closing Time": "Closing Time",
    "Allocation Basis": "Allocation Basis",
    "Allocation Limit (L)": "Allocation Limit (L)",
    "Water Type": "Water Type",
    "Source Status Time": "Source Status Time",
    "Source URL": "Source URL",
    "Source File": "Source File",
    "Source Retrieved At UTC": "Source Retrieved At UTC",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Location Resolution Status": "Location Resolution Status",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
