#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/road_nodes/kumamoto_routable_road_nodes_preprocessed.parquet
Output: data/processed/road_nodes_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/road_nodes/kumamoto_routable_road_nodes_preprocessed.parquet"
dst = ROOT / "data/processed/road_nodes_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Network Node ID": "Network Node ID",
    "Network Component ID": "Network Component ID",
    "Network Analysis Eligible": "Network Analysis Eligible",
    "Vertical Level": "Vertical Level",
    "Geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
