#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01d/road_restrictions/road_restrictions_preprocessed.parquet
Output: data/processed/road_restrictions_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01d/road_restrictions/road_restrictions_preprocessed.parquet"
dst = ROOT / "data/processed/road_restrictions_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Snapshot Time": "Snapshot Time",
    "Feature Index": "Feature Index",
    "Prefecture Name": "Prefecture Name",
    "Municipality Name": "Municipality Name",
    "Road Type": "Road Type",
    "Route Name": "Route Name",
    "Start Address": "Start Address",
    "End Address": "End Address",
    "Restriction Type": "Restriction Type",
    "Restriction Reason": "Restriction Reason",
    "Restriction Start Time": "Restriction Start Time",
    "Restriction Start Status": "Restriction Start Status",
    "Affected Length (km)": "Affected Length (km)",
    "Geometry Type": "Geometry Type",
    "Geometry JSON": "Geometry JSON",
    "Source URL": "Source URL",
    "Source File": "Source File",
    "Source Retrieved At UTC": "Source Retrieved At UTC",
    "Restriction Record Name": "Restriction Record Name",
    "Start Point Name": "Start Point Name",
    "End Point Name": "End Point Name",
    "Restriction Status": "Restriction Status",
    "Restriction Direction": "Restriction Direction",
    "Restricted Length (km)": "Restricted Length (km)",
    "Regional Bureau Code": "Regional Bureau Code",
    "Regional Bureau Name": "Regional Bureau Name",
    "Prefecture Code": "Prefecture Code",
    "Restriction Change Time": "Restriction Change Time",
    "Restriction Change Status": "Restriction Change Status",
    "Detour Available": "Detour Available",
    "Isolated Settlement Present": "Isolated Settlement Present",
    "Personal Injury Present": "Personal Injury Present",
    "Property Damage Present": "Property Damage Present",
    "Power Outage Present": "Power Outage Present",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
