#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/population_mesh_125m/kumamoto_population_mesh_125m_preprocessed.parquet
Output: data/processed/population_mesh_125m_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/population_mesh_125m/kumamoto_population_mesh_125m_preprocessed.parquet"
dst = ROOT / "data/processed/population_mesh_125m_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Mesh Code": "Mesh Code",
    "Geometry": "Geometry",
    "Disclosure Group Code": "Disclosure Group Code",
    "Disclosure Group Size": "Disclosure Group Size",
    "Disclosure Status": "Disclosure Status",
    "Aggregation Destination Mesh Code": "Aggregation Destination Mesh Code",
    "Aggregated Source Mesh Codes": "Aggregated Source Mesh Codes",
    "Total Population": "Total Population",
    "Total Households": "Total Households",
    "General Households": "General Households",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
