#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01/public_offices_halls/kumamoto_mlit_public_offices_halls_preprocessed.parquet
Output: data/processed/public_offices_halls_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01/public_offices_halls/kumamoto_mlit_public_offices_halls_preprocessed.parquet"
dst = ROOT / "data/processed/public_offices_halls_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Support Facility ID": "Support Facility ID",
    "Support Facility Type": "Support Facility Type",
    "Source Reference Year": "Source Reference Year",
    "Administrative Area Code": "Administrative Area Code",
    "Facility Class": "Facility Class",
    "Facility Name": "Facility Name",
    "Address": "Address",
    "geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
