#!/usr/bin/env python3
"""Preprocessing script for data/raw/reused_local/KE01b/administrative_areas/kumamoto_administrative_areas_preprocessed.parquet
Output: data/processed/administrative_areas_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/reused_local/KE01b/administrative_areas/kumamoto_administrative_areas_preprocessed.parquet"
dst = ROOT / "data/processed/administrative_areas_preprocessed.parquet"

# --- Load ---
df = pd.read_parquet(src)

# --- Select and rename columns ---
rename_map = {
    "Municipality Code": "Municipality Code",
    "Prefecture Name": "Prefecture Name",
    "Subprefecture Name": "Subprefecture Name",
    "District Name": "District Name",
    "Municipality Name": "Municipality Name",
    "Ward Name": "Ward Name",
    "Municipality Label": "Municipality Label",
    "Geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
